<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_about',
		'title' => 'About',
		'fields' => array (
			array (
				'key' => 'field_57a27ea8b742f',
				'label' => 'Name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => 'Enter your name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2a75eb7430',
				'label' => 'Headline',
				'name' => 'headline',
				'type' => 'text',
				'instructions' => 'Enter a brief description of what you do.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2a7a6b7431',
				'label' => 'Summary',
				'name' => 'summary',
				'type' => 'textarea',
				'instructions' => 'Enter a slightly longer summary of who you are and what you do.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_57a2a7ecb7432',
				'label' => 'Photo',
				'name' => 'photo',
				'type' => 'image',
				'instructions' => 'Upload a photo of yourself. It will display with a limit of 280px in height, so it may help to start with an image similar to those dimensions.',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_57a2a858b7433',
				'label' => 'Specialties Headline',
				'name' => 'specialties_headline',
				'type' => 'text',
				'instructions' => 'This is the headline for the "Specialties" area of the page. You can enter something other than "Specialties" if you want a different headline.',
				'default_value' => 'Specialties',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2a8fbb7434',
				'label' => 'Specialty 1 Icon',
				'name' => 'specialty_1_icon',
				'type' => 'text',
				'instructions' => 'Go to http://fontawesome.io/icons/ and choose an icon. Enter the class name such as "fa fa-book" (without the quotes.) See the theme documentation for help.',
				'default_value' => 'fa fa-book',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2a9b1b7435',
				'label' => 'Specialty 1 Title',
				'name' => 'specialty_1_title',
				'type' => 'text',
				'instructions' => 'Enter a title for this specialty. Examples: Photography, Illustration, Ecommerce, or Web Design',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2aa01b7436',
				'label' => 'Specialty 1 Description',
				'name' => 'specialty_1_description',
				'type' => 'textarea',
				'instructions' => 'Enter a brief description of this specialty.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_57a2aa27b7437',
				'label' => 'Specialty 2 Icon',
				'name' => 'specialty_2_icon',
				'type' => 'text',
				'instructions' => 'Go to http://fontawesome.io/icons/ and choose an icon. Enter the class name such as "fa fa-book" (without the quotes.) See the theme documentation for help.',
				'default_value' => 'fa fa-book',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),	
			array (
				'key' => 'field_57a2aa4cb7439',
				'label' => 'Specialty 2 Title',
				'name' => 'specialty_2_title',
				'type' => 'text',
				'instructions' => 'Enter a title for this specialty. Examples: Photography, Illustration, Ecommerce, or Web Design',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2aa6ab743b',
				'label' => 'Specialty 2 Description',
				'name' => 'specialty_2_description',
				'type' => 'textarea',
				'instructions' => 'Enter a brief description of this specialty.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),			
			array (
				'key' => 'field_57a2aa3bb7438',
				'label' => 'Specialty 3 Icon',
				'name' => 'specialty_3_icon',
				'type' => 'text',
				'instructions' => 'Go to http://fontawesome.io/icons/ and choose an icon. Enter the class name such as "fa fa-book" (without the quotes.) See the theme documentation for help.',
				'default_value' => 'fa fa-book',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2aa5db743a',
				'label' => 'Specialty 3 Title',
				'name' => 'specialty_3_title',
				'type' => 'text',
				'instructions' => 'Enter a title for this specialty. Examples: Photography, Illustration, Ecommerce, or Web Design',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a2aa89b743c',
				'label' => 'Specialty 3 Description',
				'name' => 'specialty_3_description',
				'type' => 'textarea',
				'instructions' => 'Enter a brief description of this specialty.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-about.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'discussion',
				1 => 'comments',
			),
		),
		'menu_order' => 0,
	));
}


?>